Update patch set 2
Patch Set 2:

TypeError: b2a_base64() argument 1 must be convertible to a buffer, not Base64Keywords

Patch-set: 2
Label: Verified=0